In [2]:
import numpy as np
from numpy.linalg import inv
from scipy import linalg

In [10]:
def steepest_descent(A, b):
    m,n = A.shape
    if m!= n:
        b = A.T@b
        A = A.T@A
    x = np.zeros(A.shape[0])
    
    for i in range(10000):
        r = b - A@x

        up = (np.inner(r,r))
        down = (np.inner(r,A@r))
        # up = r.T@r
        # down = r.T@A@r
        alpha = up/np.maximum(0.00001,down)
        x = x + alpha * r

        
        if i!=0:
            if abs((x-x_temp).all()) < 0.001:
                print(i)
                break
        x_temp =x 

    return x

In [11]:
A = np.array([[2.0,1.0],[5.0,7.0]])
b = np.array([11.0,13.0])

A = np.array([[1.  , 0.18, 0.89],
       [1.  , 1.  , 0.26],
       [1.  , 0.92, 0.11],
       [1.  , 0.07, 0.37],
       [1.  , 0.85, 0.16],
       [1.  , 0.99, 0.41],
       [1.  , 0.87, 0.47]])

b = np.array([109.85,155.72,137.66, 76.17,139.75,162.6,151.77])

In [12]:
def get_A_omega(A, omega):
    omega = sorted(omega)
    A_omega = A[:,omega]

    return A_omega

In [13]:
def OMP(A,b, non_zeros):
    omega = []
    x_omega = np.array([])
    A_omega = get_A_omega(A, omega)

    for i in range(non_zeros):

        r = b - A_omega@x_omega
        c = A.T@r
        c= c[np.nonzero(c)]

        omega.append(c.argmax())
        omega = list(set(omega))

        A_omega = get_A_omega(A, omega)
        # x_omega= linalg.lstsq(A_omega, b)[0]
        x_omega = steepest_descent(A_omega,b)
    return x_omega

In [16]:
OMP(A,b, 3)

1


array([52.41171523, 90.69316292, 46.46269338])

In [15]:
steepest_descent(A,b)

array([52.41171523, 90.69316292, 46.46269338])

In [4]:
abs(np.array([1,-2.2,2]))

array([1. , 2.2, 2. ])