In [3]:
import numpy as np

In [98]:
def steepest_descent(A, b):
    m,n = A.shape
    if m!= n:
        b = A.T@b
        A = A.T@A
    x = np.zeros(A.shape[0])
    print(x)
    for i in range(10000):

        r = b - A@x
        up = (np.inner(r,r))
        down = (np.inner(r,A@r))
        # up = r.T@r
        # down = r.T@A@r
        print(up)
        alpha = up/down
        x_temp =x 
        x = x + alpha * r

        if abs((x-x_temp).all()) < 0.001:
            print(i)
            break

    return x

In [99]:
A = np.array([[1,2],[2,2], [3,4]])
b = np.array([1,2,3])


In [100]:
steepest_descent(A, b)

[0. 0.]
520.0
0.06320527157441785
0.10448218362301727
1.2699663058804448e-05
2.0993320566109292e-05
2.551708706988642e-09
4.218130699189703e-09
5.127078752990059e-13
8.475378582379014e-13
1.0301705774427786e-16
1.70290788576359e-16
2.069860239349547e-20
3.421006300331673e-20
4.157173908213518e-24
8.710867172714567e-24
1.2621774483536189e-27
7.099748146989106e-28
3.1554436208840472e-30
17


array([1.00000000e+00, 2.69765597e-15])

In [101]:
A = np.array([[2.0,1.0],[5.0,7.0]])
b = np.array([11.0,13.0])


In [102]:
steepest_descent(A,b)

[0. 0.]
290.0
73.71176700935075
0.055837547604089814
0.014192704480573679
1.0751143870326992e-05
2.7327096967397597e-06
2.070060371399175e-09
5.261648545186991e-10
3.9857617285155706e-13
1.0130949584196847e-13
7.674311338219614e-17
1.950645134715832e-17
1.4776698904751453e-20
3.755935160006066e-21
2.8274352564931505e-24
7.135467768777514e-25
1.7575820968324143e-27
3.060780312257526e-28
3.8496412174785376e-27
1.672385119068545e-28
2.8556764769000627e-27
2.8398992587956425e-29
21


array([ 7.11111111, -3.22222222])

In [103]:
A = np.array([[1.  , 0.18, 0.89],
       [1.  , 1.  , 0.26],
       [1.  , 0.92, 0.11],
       [1.  , 0.07, 0.37],
       [1.  , 0.85, 0.16],
       [1.  , 0.99, 0.41],
       [1.  , 0.87, 0.47]])

b = np.array([109.85,155.72,137.66, 76.17,139.75,162.6,151.77])

steepest_descent(A,b)

[0. 0. 0.]
1505734.9385586602
344.7680662720257
41.38590653714851
77.60456945167807
34.90004117637905
66.56651275065322
30.183643772934815
58.0825424809967
26.44644213992349
51.116405963405185
23.322227948001917
45.17536913794158
20.632059379376834
40.00632842058311
18.280057375186825
35.46358314522248
16.208077426846312
31.451531166872787
14.37602172482511
27.89969986267247
12.753210014528118
24.751673250018612
11.31450614681202
21.95999731267148
10.038495455320536
19.48367532720785
8.906555370531333
17.28680385658194
7.902323648706782
15.337727860713265
7.0113511965028215
13.608446542211102
6.220847081725616
12.074152342681824
5.519474865097296
10.71285006873184
4.897181499605319
9.505030939502548
4.345049607646822
8.433388481245842
3.8551681522556893
7.48256862240484
3.4205184294798032
6.638948887079824
3.034873229384107
5.890442876011943
2.6927075001014393
5.2263269583906755
2.38911914104133
4.637086574348521
2.119758750505833
4.114279896273346
1.8807673042007336
3.6504168744570773

array([52.41149905, 90.69331739, 46.46296549])